// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// 商品を新規登録する
	createProduct: (req: ProductCreateRequest) => typedError<ProductCreateResult, CmdError>(__TAURI_INVOKE("create_product", { req })),
	// 商品情報を更新する
	updateProduct: (productCode: string, req: ProductUpdateRequest_Deserialize) => typedError<ProductUpdateResult, CmdError>(__TAURI_INVOKE("update_product", { productCode, req })),
	/**
	 *  廃番状態を切り替える
	 *
	 *  戻り値は is_discontinued の新しい値。
	 */
	toggleDiscontinue: (productCode: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("toggle_discontinue", { productCode })),
	// 商品を検索する（ページング対応）
	searchProducts: (query: ProductSearchQuery) => typedError<PaginatedResult<ProductWithRelations>, CmdError>(__TAURI_INVOKE("search_products", { query })),
	// 部門選択候補を全件取得する
	listDepartments: () => typedError<Department[], CmdError>(__TAURI_INVOKE("list_departments")),
	// 取引先選択候補を全件取得する
	listSuppliers: () => typedError<Supplier[], CmdError>(__TAURI_INVOKE("list_suppliers")),
	/**
	 *  商品詳細を取得する
	 *
	 *  BIZ層（product_service）経由で呼び出す。
	 */
	getProduct: (productCode: string) => typedError<ProductWithRelations, CmdError>(__TAURI_INVOKE("get_product", { productCode })),
	/**
	 *  商品マスタCSVのプレビューを返す（読み取り専用）
	 *
	 *  ファイル内容を解析し、有効行・エラー行・重複行に分類して返す。
	 *  DB書込みは行わない。
	 */
	previewImport: (fileBytes: number[]) => typedError<ImportPreview, CmdError>(__TAURI_INVOKE("preview_import", { fileBytes })),
	/**
	 *  プレビュー済みの一括インポートを確定する
	 *
	 *  valid_rows の INSERT/UPDATE と、overwrite_codes の上書き処理をトランザクション内で実行。
	 */
	commitImport: (validRows: ImportRow[], overwriteCodes: string[]) => typedError<ProductImportResult, CmdError>(__TAURI_INVOKE("commit_import", { validRows, overwriteCodes })),
	/**
	 *  入庫記録を作成する
	 *
	 *  44-cmd-inventory.md §23.1 create_receiving
	 */
	createReceiving: (req: ReceivingCreateRequest) => typedError<ReceivingCreateResult, CmdError>(__TAURI_INVOKE("create_receiving", { req })),
	/**
	 *  入庫記録一覧を返す
	 *
	 *  44-cmd-inventory.md §23.2 list_receivings
	 */
	listReceivings: (page: number, perPage: number, dateFrom: string | null, dateTo: string | null) => typedError<PaginatedResult<ReceivingRecordWithSupplier>, CmdError>(__TAURI_INVOKE("list_receivings", { page, perPage, dateFrom, dateTo })),
	/**
	 *  入庫記録詳細を返す
	 *
	 *  65-inventory-record-traceability.md §65.7 getReceivingRecord
	 */
	getReceivingRecord: (recordId: number) => typedError<ReceivingRecordDetail, CmdError>(__TAURI_INVOKE("get_receiving_record", { recordId })),
	/**
	 *  返品・交換記録を作成する
	 *
	 *  44-cmd-inventory.md §23.4 create_return
	 */
	createReturn: (req: ReturnCreateRequest) => typedError<ReturnCreateResult, CmdError>(__TAURI_INVOKE("create_return", { req })),
	/**
	 *  返品・交換記録一覧を返す
	 *
	 *  44-cmd-inventory.md §23.5 list_returns
	 */
	listReturns: (page: number, perPage: number, dateFrom: string | null, dateTo: string | null) => typedError<PaginatedResult<ReturnRecordSummary>, CmdError>(__TAURI_INVOKE("list_returns", { page, perPage, dateFrom, dateTo })),
	/**
	 *  返品・交換記録詳細を返す
	 *
	 *  65-inventory-record-traceability.md §65.7 getReturnRecord
	 */
	getReturnRecord: (recordId: number) => typedError<ReturnRecordDetail, CmdError>(__TAURI_INVOKE("get_return_record", { recordId })),
	/**
	 *  手動販売出庫を作成する
	 *
	 *  44-cmd-inventory.md §23.6 create_manual_sale
	 *  PLU警告がある場合は2段階確認フロー（needs_confirmation + confirmation_token）
	 */
	createManualSale: (req: ManualSaleCreateRequest) => typedError<ManualSaleCreateResult, CmdError>(__TAURI_INVOKE("create_manual_sale", { req })),
	/**
	 *  手動販売記録詳細を返す
	 *
	 *  65-inventory-record-traceability.md §65.7 getManualSaleRecord
	 */
	getManualSaleRecord: (recordId: number) => typedError<ManualSaleRecordDetail, CmdError>(__TAURI_INVOKE("get_manual_sale_record", { recordId })),
	/**
	 *  廃棄・破損記録を作成する
	 *
	 *  44-cmd-inventory.md §23.7 create_disposal
	 */
	createDisposal: (req: DisposalCreateRequest) => typedError<DisposalCreateResult, CmdError>(__TAURI_INVOKE("create_disposal", { req })),
	/**
	 *  廃棄・破損記録一覧を返す
	 *
	 *  44-cmd-inventory.md §23.7 list_disposals
	 */
	listDisposals: (page: number, perPage: number, dateFrom: string | null, dateTo: string | null) => typedError<PaginatedResult<DisposalRecordSummary>, CmdError>(__TAURI_INVOKE("list_disposals", { page, perPage, dateFrom, dateTo })),
	/**
	 *  入出庫履歴ハブの業務記録一覧を返す
	 *
	 *  65-inventory-record-traceability.md §65.7 listInventoryRecords
	 */
	listInventoryRecords: (query: InventoryRecordQuery) => typedError<PaginatedResult<InventoryRecordSummary>, CmdError>(__TAURI_INVOKE("list_inventory_records", { query })),
	/**
	 *  廃棄・破損記録詳細を返す
	 *
	 *  65-inventory-record-traceability.md §65.7 getDisposalRecord
	 */
	getDisposalRecord: (recordId: number) => typedError<DisposalRecordDetail, CmdError>(__TAURI_INVOKE("get_disposal_record", { recordId })),
	/**
	 *  商品の在庫詳細を取得する（最終入庫日・最終販売日を含む）
	 *
	 *  44-cmd-inventory.md §23.8 get_stock_detail
	 */
	getStockDetail: (productCode: string) => typedError<StockDetail, CmdError>(__TAURI_INVOKE("get_stock_detail", { productCode })),
	/**
	 *  在庫が閾値以下の商品を一覧取得する
	 *
	 *  44-cmd-inventory.md §23.8 list_low_stock
	 */
	listLowStock: (includeDiscontinued: boolean) => typedError<ProductWithRelations[], CmdError>(__TAURI_INVOKE("list_low_stock", { includeDiscontinued })),
	/**
	 *  商品別の在庫変動履歴をフィルタ付きでページング取得する
	 *
	 *  44-cmd-inventory.md §23.8 list_movements
	 */
	listMovements: (query: MovementQuery) => typedError<PaginatedResult<MovementRecord>, CmdError>(__TAURI_INVOKE("list_movements", { query })),
	/**
	 *  Z004ファイルを受け取り、プレビューデータを返す
	 *
	 *  docs/function-design/41-cmd-pos.md §17.5 parse_and_validate_csv
	 */
	parseAndValidateCsv: (fileBytes: number[], filename: string) => typedError<ParseAndValidateResponse, CmdError>(__TAURI_INVOKE("parse_and_validate_csv", { fileBytes, filename })),
	/**
	 *  プレビュー済みデータの取込みを確定する
	 *
	 *  docs/function-design/41-cmd-pos.md §17.5 commit_csv_import
	 */
	commitCsvImport: (previewToken: string, overwriteConfirmed: boolean) => typedError<ImportResult, CmdError>(__TAURI_INVOKE("commit_csv_import", { previewToken, overwriteConfirmed })),
	/**
	 *  CSV取込みをロールバック（論理無効化）する
	 *
	 *  docs/function-design/41-cmd-pos.md §17.5 rollback_csv_import
	 */
	rollbackCsvImport: (csvImportId: number) => typedError<RollbackResult, CmdError>(__TAURI_INVOKE("rollback_csv_import", { csvImportId })),
	/**
	 *  CSV取込み履歴の一覧を返す
	 *
	 *  docs/function-design/41-cmd-pos.md §17.5 list_csv_imports
	 */
	listCsvImports: (page: number, perPage: number) => typedError<PaginatedResult<CsvImport>, CmdError>(__TAURI_INVOKE("list_csv_imports", { page, perPage })),
	parseAndValidateDailyReport: (files: DailyReportSourceFileRequest[]) => typedError<DailyReportPreviewResponse, CmdError>(__TAURI_INVOKE("parse_and_validate_daily_report", { files })),
	commitDailyReportImport: (previewToken: string, overwriteConfirmed: boolean) => typedError<DailyReportImportResult, CmdError>(__TAURI_INVOKE("commit_daily_report_import", { previewToken, overwriteConfirmed })),
	rollbackDailyReportImport: (dailyReportImportId: number) => typedError<DailyReportRollbackResult, CmdError>(__TAURI_INVOKE("rollback_daily_report_import", { dailyReportImportId })),
	listDailyReportImports: (page: number, perPage: number, dateFrom: string | null, dateTo: string | null) => typedError<PaginatedResult<DailyReportImport>, CmdError>(__TAURI_INVOKE("list_daily_report_imports", { page, perPage, dateFrom, dateTo })),
	/**
	 *  PLUファイルを生成して返す。DB状態は更新しない。
	 *
	 *  docs/function-design/41-cmd-pos.md §17.6 prepare_plu_export
	 */
	preparePluExport: (mode: string) => typedError<PluExportPrepareResponse, CmdError>(__TAURI_INVOKE("prepare_plu_export", { mode })),
	/**
	 *  PLUファイル保存済み確認を受け、対象商品を未反映から外す
	 *
	 *  docs/function-design/41-cmd-pos.md §17.6 confirm_plu_export_saved
	 */
	confirmPluExportSaved: (productCodes: string[]) => typedError<PluExportConfirmResponse, CmdError>(__TAURI_INVOKE("confirm_plu_export_saved", { productCodes })),
	/**
	 *  PLU書出しが必要な商品一覧を返す
	 *
	 *  docs/function-design/41-cmd-pos.md §17.6 list_plu_dirty
	 */
	listPluDirty: () => typedError<ProductResponse[], CmdError>(__TAURI_INVOKE("list_plu_dirty")),
	// 指定日の売上レポートを取得する
	getDailySales: (date: string) => typedError<DailySalesReport, CmdError>(__TAURI_INVOKE("get_daily_sales", { date })),
	/**
	 *  指定月の売上レポートを取得する
	 *
	 *  mode は文字列で受け取り CMD 層で SalesMode enum に変換する。
	 *  フロントエンド側の実装を単純化するための設計判断（§22.4、H-1: response serialize のみ rename_all で snake_case 化）。
	 */
	getMonthlySales: (month: string, mode: string) => typedError<MonthlySalesReport, CmdError>(__TAURI_INVOKE("get_monthly_sales", { month, mode })),
	/**
	 *  売上データをCSVファイルとしてエクスポートする
	 *
	 *  42-cmd-sales-stocktake.md §22.4 export_sales_csv
	 *
	 *  `report_type` は `SalesReportType` enum を直接受け取る（H-5 / Q-6 A 案）。
	 *  frontend bindings の `exportSalesCsv(reportType: SalesReportType, target: string)` で
	 *  `"daily" | "monthly_by_product" | "monthly_by_department"` literal union を渡し、
	 *  serde::Deserialize で直接 enum に変換される（文字列 validation 不要、type safety 最大化）。
	 */
	exportSalesCsv: (reportType: SalesReportType, target: string) => typedError<SalesExportResponse, CmdError>(__TAURI_INVOKE("export_sales_csv", { reportType, target })),
	/**
	 *  進行中の棚卸しを取得する
	 *
	 *  BIZ層（stocktake_service）経由で呼び出す。読み取り専用。
	 */
	getActiveStocktake: () => typedError<{
	id: number,
	started_at: string,
	completed_at: string | null,
	status: string,
	total_cost: number | null,
} | null, CmdError>(__TAURI_INVOKE("get_active_stocktake")),
	/**
	 *  新しい棚卸しを開始する
	 *
	 *  進行中の棚卸しが既にある場合は stocktake_in_progress エラー。
	 */
	startStocktake: () => typedError<StartStocktakeResult, CmdError>(__TAURI_INVOKE("start_stocktake")),
	/**
	 *  棚卸しアイテム一覧を取得する
	 *
	 *  BIZ層（stocktake_service）経由で呼び出す。読み取り専用。
	 */
	getStocktakeItems: (stocktakeId: number, departmentId: number | null, countedOnly: boolean | null, page: number, perPage: number) => typedError<StocktakeItemListResponse, CmdError>(__TAURI_INVOKE("get_stocktake_items", { stocktakeId, departmentId, countedOnly, page, perPage })),
	/**
	 *  商品コードまたはJANコードで棚卸しアイテムを取得する
	 *
	 *  BIZ層（stocktake_service）経由で呼び出す。読み取り専用。
	 */
	findStocktakeItem: (stocktakeId: number, code: string) => typedError<{
	id: number,
	stocktake_id: number,
	product_code: string,
	name: string,
	department_name: string,
	system_stock: number,
	actual_count: number | null,
	counted_at: string | null,
	current_stock: number,
} | null, CmdError>(__TAURI_INVOKE("find_stocktake_item", { stocktakeId, code })),
	/**
	 *  最後に完了した棚卸しを取得する
	 *
	 *  完了済みがない場合は None を返す。読み取り専用。
	 */
	getLastCompletedStocktake: () => typedError<{
	stocktake_id: number,
	completed_at: string,
	total_cost: number,
} | null, CmdError>(__TAURI_INVOKE("get_last_completed_stocktake")),
	/**
	 *  棚卸しアイテムのカウントを更新する
	 *
	 *  actual_count < 0 は防御的チェックでブロック（BIZ層にも同じチェックあり）。
	 */
	updateCount: (stocktakeItemId: number, actualCount: number) => typedError<UpdateCountResult, CmdError>(__TAURI_INVOKE("update_count", { stocktakeItemId, actualCount })),
	/**
	 *  棚卸しを確定する
	 *
	 *  force_fill=true で未入力をシステム在庫と同じとみなす。
	 *  確定後に整合性チェック（D-2統合）を自動実行し、結果を含めて返す。
	 */
	completeStocktake: (stocktakeId: number, forceFill: boolean) => typedError<StocktakeResult, CmdError>(__TAURI_INVOKE("complete_stocktake", { stocktakeId, forceFill })),
	/**
	 *  在庫整合性チェックを実行する
	 *
	 *  全商品の products.stock_quantity と SUM(inventory_movements.quantity) を突合。
	 *  読み取り専用。
	 */
	runIntegrityCheck: () => typedError<IntegrityResult, CmdError>(__TAURI_INVOKE("run_integrity_check")),
	/**
	 *  指定商品の在庫を整合性チェック結果に基づいて補正する
	 *
	 *  stock_quantity を movements 合計値に補正し、操作ログに記録する。
	 */
	fixIntegrity: (productCodes: string[]) => typedError<IntegrityFixResult, CmdError>(__TAURI_INVOKE("fix_integrity", { productCodes })),
	// 全設定を取得する（§43.3）
	getSettings: () => typedError<AppSetting[], CmdError>(__TAURI_INVOKE("get_settings")),
	// 設定値を更新する（§43.4）
	updateSetting: (request: UpdateSettingRequest) => typedError<null, CmdError>(__TAURI_INVOKE("update_setting", { request })),
	// 操作ログ一覧を取得する（§43.5）
	listLogs: (query: LogQuery) => typedError<PaginatedResult<OperationLog>, CmdError>(__TAURI_INVOKE("list_logs", { query })),
	listLogOperationTypes: () => typedError<string[], CmdError>(__TAURI_INVOKE("list_log_operation_types")),
	// バックアップを作成する（§43.6）
	createBackup: () => typedError<BackupResult, CmdError>(__TAURI_INVOKE("create_backup")),
	/**
	 *  自動バックアップチェック（§43.7）
	 *
	 *  フロントエンドの setInterval(60秒) から呼ばれる。
	 */
	checkAutoBackup: () => typedError<boolean, CmdError>(__TAURI_INVOKE("check_auto_backup")),
	// バックアップ一覧を取得する（§43.8）
	listBackups: () => typedError<BackupInfo[], CmdError>(__TAURI_INVOKE("list_backups")),
	/**
	 *  実効バックアップ保存先を取得する（§43.8.1）
	 *
	 *  `backup_path` 未設定時にアプリ既定フォルダ（`app_data/backups`）を利用者へ提示するための
	 *  読み取り専用コマンド。既存ヘルパ `get_backup_dir` を呼ぶだけの薄いラッパー。
	 */
	getEffectiveBackupDir: () => typedError<string, CmdError>(__TAURI_INVOKE("get_effective_backup_dir")),
	/**
	 *  バックアップから復元する（§43.9）
	 *
	 *  DB接続の所有権を移転するため、Mutex内の接続をstd::mem::replaceで取り出す。
	 *  **? 演算子はreplace後に使用禁止** — dummy接続がguardに残るのを防ぐため。
	 */
	restoreBackup: (request: RestoreBackupRequest) => typedError<null, CmdError>(__TAURI_INVOKE("restore_backup", { request })),
	// レシート画像を保存する（§43.10）
	saveReceiptImage: (request: SaveImageRequest) => typedError<SaveImageResponse, CmdError>(__TAURI_INVOKE("save_receipt_image", { request })),
};

/* Types */
// 差異補正アイテム
export type AdjustedItem = {
	product_code: string,
	product_name: string,
	system_stock: number,
	actual_count: number,
	difference: number,
	stock_after: number,
};

/**
 *  アプリ設定の行マッピング（第6段階追加）
 *
 *  20-io-product-repo.md §2.8
 */
export type AppSetting = {
	key: string,
	value: string,
	updated_at: string,
};

/**
 *  バックアップファイル情報（一覧表示用）
 *
 *  71-mnt-backup.md §71.3
 */
export type BackupInfo = {
	file_name: string,
	file_path: string,
	size_bytes: number,
	created_at: string,
};

/**
 *  バックアップ作成結果
 *
 *  71-mnt-backup.md §71.3
 */
export type BackupResult = {
	file_path: string,
	file_name: string,
	size_bytes: number,
};

/**
 *  UI向け構造化エラー
 *
 *  docs/function-design/40-cmd-product.md §5.3 + 41-cmd-pos.md §17.4
 */
export type CmdError = {
	// エラー分類: "validation" / "duplicate" / "not_found" / "internal" / "import_error" / "idempotency_conflict" / "stocktake_in_progress" / "stocktake_not_in_progress"
	kind: string,
	// 利用者向け日本語メッセージ
	message: string,
	// バリデーションエラー時のフィールド名
	field: string | null,
};

/**
 *  csv_imports テーブルの行マッピング
 *
 *  24-io-csv-import-repo.md §14.2
 */
export type CsvImport = {
	id: number,
	filename: string,
	settlement_date: string,
	file_hash: string,
	total_items: number,
	total_amount: number,
	skipped_count: number,
	status: string,
	imported_at: string,
};

export type DailyReportDepartmentLinePreview = {
	department_id: number | null,
	raw_department_name: string,
	normalized_department_name: string | null,
	amount: number,
	quantity: number | null,
	count: number | null,
	sort_order: number,
};

export type DailyReportDuplicateCheck = {
	status: DailyReportDuplicateStatus,
	existing_import_id: number | null,
};

export type DailyReportDuplicateStatus = "NoDuplicate" | "AlreadyImported" | "OverwriteRequired";

export type DailyReportFileInfo = {
	report_date: string,
	bundle_hash: string,
	source_files: DailyReportSourceFileInfo[],
};

/**
 *  daily_report_imports テーブルの行マッピング
 *
 *  24-io-csv-import-repo.md §14.2 / §14.14-14.20
 */
export type DailyReportImport = {
	id: number,
	report_date: string,
	source_adapter: string,
	bundle_hash: string,
	source_files_json: string,
	gross_amount: number | null,
	net_amount: number | null,
	status: string,
	imported_at: string,
	rolled_back_at: string | null,
	note: string | null,
};

export type DailyReportImportResult = {
	daily_report_import_id: number,
	status: string,
	report_date: string,
	gross_amount: number | null,
	net_amount: number | null,
	warning_count: number,
};

export type DailyReportPaymentLinePreview = {
	payment_key: string,
	label: string,
	amount: number | null,
	count: number | null,
	sort_order: number,
};

export type DailyReportPreviewData = {
	file_info: DailyReportFileInfo,
	totals: DailyReportTotals,
	payment_summary: DailyReportPaymentLinePreview[],
	department_summary: DailyReportDepartmentLinePreview[],
	warnings: DailyReportWarning[],
	duplicate_check: DailyReportDuplicateCheck,
	preview_created_at: string,
};

export type DailyReportPreviewResponse = {
	preview_data: DailyReportPreviewData,
	preview_token: string,
};

export type DailyReportRollbackResult = {
	daily_report_import_id: number,
	status: string,
	rolled_back_at: string | null,
};

export type DailyReportSourceFileInfo = {
	source: DailyReportSourceKind,
	filename: string,
	file_hash: string,
	size_bytes: number,
};

export type DailyReportSourceFileRequest = {
	filename: string,
	file_bytes: number[],
};

export type DailyReportSourceKind = "Z001" | "Z002" | "Z005";

export type DailyReportTotals = {
	gross_amount: number | null,
	net_amount: number | null,
};

export type DailyReportWarning = {
	code: string,
	message: string,
	source_file: DailyReportSourceKind | null,
	line_no: number | null,
};

// 日次売上アイテム（BIZ公開型。DB型からマッピング）
export type DailySaleItem = {
	product_code: string,
	name: string,
	department_name: string,
	department_id: number,
	quantity: number,
	amount: number,
	source: string,
};

// 日次売上レポート
export type DailySalesReport = {
	date: string,
	items: DailySaleItem[],
	department_subtotals: DeptSubtotal[],
	grand_total: GrandTotal,
	official_daily_report: OfficialDailyReportSummary | null,
};

/**
 *  部門マスタの行マッピング
 *
 *  db-design/master-tables.md departments
 */
export type Department = {
	id: number,
	name: string,
	z005_name: string | null,
	code_prefix: string | null,
	next_seq: number,
	created_at: string,
};

// 部門小計
export type DeptSubtotal = {
	department_id: number,
	department_name: string,
	quantity: number,
	amount: number,
};

// 廃棄・破損記録リクエスト（31-biz-inventory-service.md §12.6）
export type DisposalCreateRequest = {
	idempotency_key: string,
	disposal_date: string,
	items: DisposalItemInput[],
};

// 廃棄・破損記録の結果
export type DisposalCreateResult = {
	record_id: number,
	created: boolean,
	idempotent_replay: boolean,
	stock_warnings: string[],
};

export type DisposalItemInput = {
	product_code: string,
	disposal_type: string,
	quantity: number,
	cost_price: number,
	reason: string,
};

// 廃棄・破損詳細
export type DisposalRecordDetail = {
	id: number,
	disposal_date: string,
	status: string,
	created_at: string,
	items: DisposalRecordDetailItem[],
	total_loss_cost: number,
	movements: MovementRecord[],
};

// 廃棄・破損詳細の明細行
export type DisposalRecordDetailItem = {
	id: number,
	product_code: string,
	product_name: string,
	department_name: string,
	stock_unit: string,
	disposal_type: string,
	quantity: number,
	cost_price: number,
	reason: string,
	line_loss_cost: number,
};

// 廃棄記録一覧表示用
export type DisposalRecordSummary = {
	id: number,
	disposal_date: string,
	created_at: string,
};

// 重複チェック結果
export type DuplicateCheck = {
	status: DuplicateStatus,
	// OverwriteRequired時のみSome
	existing_import_id: number | null,
};

// 重複チェックのステータス
export type DuplicateStatus =
// 問題なし
"NoDuplicate" |
// 同settlement_date、別ファイル → 上書き確認
"OverwriteRequired";

// エラー行（フロント送信 + キャッシュ兼用）
export type ErrorRow = {
	line_no: number,
	// JAN正規化前にエラーならNone
	normalized_jan: string | null,
	name: string,
	raw_quantity: string,
	raw_amount: string,
	// "unmatched_product" / "invalid_format" / "invalid_jan" / "invalid_number"
	error_type: string,
	// 利用者向け日本語メッセージ
	error_message: string,
};

// エラーサマリ
export type ErrorSummary = {
	// エラー行の総数
	count: number,
	// 最大100件（UI表示の上限）
	items: ErrorRow[],
};

// ファイル情報
export type FileInfo = {
	filename: string,
	// YYYY-MM-DD
	settlement_date: string,
	// SHA-256 hex、小文字64文字
	file_hash: string,
};

// 総合計
export type GrandTotal = {
	quantity: number,
	amount: number,
};

// 重複行（product_code が既存）
export type ImportDuplicateRow = {
	line_no: number,
	import_row: ImportRow,
	existing_product_code: string,
};

// バリデーションエラー行
export type ImportErrorRow = {
	line_no: number,
	raw_data: { [key in string]: string },
	errors: string[],
};

// インポートプレビュー結果
export type ImportPreview = {
	valid_rows: ImportRow[],
	error_rows: ImportErrorRow[],
	duplicate_rows: ImportDuplicateRow[],
};

// commit_csv_import の結果
export type ImportResult = {
	csv_import_id: number,
	// "completed" / "completed_partial"
	status: string,
	total_items: number,
	total_amount: number,
	skipped_count: number,
};

/**
 *  一括インポート用行データ
 *
 *  オプション項目は None = CSV に値なし。デフォルト化は commit_import の INSERT 時のみ。
 */
export type ImportRow = {
	line_no: number,
	product_code: string,
	name: string,
	department_id: number,
	selling_price: number,
	cost_price: number,
	tax_rate: string,
	stock_unit: string | null,
	initial_stock: number | null,
	jan_code: string | null,
	maker_code: string | null,
	supplier_id: number | null,
	pos_stock_sync: boolean | null,
};

// 整合性補正結果
export type IntegrityFixResult = {
	fixed_count: number,
	skipped_count: number,
	adjustments: StockAdjustment[],
};

// 不整合アイテム
export type IntegrityMismatch = {
	product_code: string,
	name: string,
	stock_quantity: number,
	movements_sum: number,
	difference: number,
};

// 整合性チェック結果
export type IntegrityResult = {
	mismatches: IntegrityMismatch[],
	mismatch_count: number,
	checked_count: number,
};

/**
 *  入出庫履歴ハブの検索条件
 *
 *  65-inventory-record-traceability.md §65.4
 */
export type InventoryRecordQuery = {
	record_type: string | null,
	date_from: string | null,
	date_to: string | null,
	record_id: number | null,
	product_keyword: string | null,
	department_id: number | null,
	status: string | null,
	page: number,
	per_page: number,
};

/**
 *  入出庫履歴ハブの1行
 *
 *  初回実装は disposal_record のみを実データとして返す。
 */
export type InventoryRecordSummary = {
	record_type: string,
	record_id: number,
	business_date: string,
	representative_item: string,
	item_count: number,
	status: string,
	created_at: string,
	detail_route: string,
};

// 前回完了棚卸しサマリ（UI-10-D5）
export type LastStocktakeSummary = {
	stocktake_id: number,
	completed_at: string,
	total_cost: number,
};

export type LogQuery = {
	page: number,
	per_page: number,
	operation_type: string | null,
	start_date: string | null,
	end_date: string | null,
};

// 手動販売出庫リクエスト（31-biz-inventory-service.md §12.5）
export type ManualSaleCreateRequest = {
	idempotency_key: string,
	sale_date: string,
	reason: string,
	note: string | null,
	items: ManualSaleItemInput[],
	confirmation_token: string | null,
};

// 手動販売出庫の結果
export type ManualSaleCreateResult = {
	sale_id: number | null,
	created: boolean,
	idempotent_replay: boolean,
	plu_warnings: string[],
	stock_warnings: string[],
	needs_confirmation: boolean,
	confirmation_token: string | null,
};

export type ManualSaleItemInput = {
	product_code: string,
	quantity: number,
	amount: number,
};

// 手動販売記録詳細
export type ManualSaleRecordDetail = {
	id: number,
	sale_date: string,
	reason: string,
	note: string | null,
	status: string,
	created_at: string,
	items: ManualSaleRecordDetailItem[],
	total_amount: number,
	movements: MovementRecord[],
};

// 手動販売記録詳細の明細行
export type ManualSaleRecordDetailItem = {
	id: number,
	product_code: string,
	product_name: string,
	department_name: string,
	stock_unit: string,
	quantity: number,
	amount: number,
};

// マッチ成功サマリ
export type MatchedSummary = {
	// 紐付け成功件数
	count: number,
	// matched_rows の amount 合計
	total_amount: number,
	// グループコード商品の紐付け警告等
	warnings: string[],
};

// 月次売上集計アイテム（ランキング付き）
export type MonthlySaleItem = {
	key: string,
	label: string,
	quantity: number,
	amount: number,
	ranking: number,
};

// 月次売上レポート
export type MonthlySalesReport = {
	month: string,
	mode: SalesMode,
	items: MonthlySaleItem[],
	prev_month_comparison: MonthlySaleItem[] | null,
	official_department_totals: OfficialMonthlyDepartmentTotal[] | null,
};

/**
 *  在庫変動履歴の検索条件
 *
 *  44-cmd-inventory.md §23.8 list_movements
 */
export type MovementQuery = {
	product_code: string,
	date_from: string | null,
	date_to: string | null,
	movement_type: string | null,
	page: number,
	per_page: number,
};

/**
 *  在庫変動履歴1件
 *
 *  44-cmd-inventory.md §23.8 list_movements
 */
export type MovementRecord = {
	id: number,
	product_code: string,
	movement_type: string,
	quantity: number,
	stock_after: number,
	reference_type: string | null,
	reference_id: number | null,
	source: MovementSourceLink | null,
	note: string | null,
	created_at: string,
};

/**
 *  在庫変動の元業務記録リンク
 *
 *  44-cmd-inventory.md §23.8 list_movements
 */
export type MovementSourceLink = {
	label: string,
	route: string,
};

// レジ日報由来の部門別集計行
export type OfficialDailyDepartmentLine = {
	department_id: number | null,
	raw_department_name: string,
	normalized_department_name: string | null,
	amount: number,
	quantity: number | null,
	count: number | null,
};

// レジ日報由来の支払集計行
export type OfficialDailyPaymentLine = {
	payment_key: string,
	label: string,
	amount: number | null,
	count: number | null,
};

// レジ日報由来の公式日次サマリ
export type OfficialDailyReportSummary = {
	daily_report_import_id: number,
	report_date: string,
	gross_amount: number | null,
	net_amount: number | null,
	payment_lines: OfficialDailyPaymentLine[],
	department_lines: OfficialDailyDepartmentLine[],
	warnings: string[],
};

// レジ日報由来の月次公式部門集計行
export type OfficialMonthlyDepartmentTotal = {
	department_id: number | null,
	label: string,
	amount: number,
	quantity: number | null,
	count: number | null,
};

/**
 *  操作ログの行マッピング（第6段階追加）
 *
 *  20-io-product-repo.md §2.8
 */
export type OperationLog = {
	id: number,
	operation_type: string,
	summary: string,
	detail_json: string | null,
	created_at: string,
};

/**
 *  ページネーション付き検索結果
 *
 *  20-io-product-repo.md §2.10
 */
export type PaginatedResult<T> = {
	items: T[],
	total_count: number,
	page: number,
	per_page: number,
};

// parse_and_validate_csv のレスポンス（フロントエンド返却用）
export type ParseAndValidateResponse = {
	// プレビューデータ（表示用）
	preview_data: PreviewData,
	// commit時に送り返すトークン
	preview_token: string,
};

export type PluExcludedProductResponse = {
	product_code: string,
	jan_code: string | null,
	name: string,
	reason: string,
};

// PLU保存済み確認レスポンス（フロントエンド返却用）
export type PluExportConfirmResponse = {
	updated_count: number,
	confirmed_at: string,
};

/**
 *  PLUファイル生成レスポンス（フロントエンド返却用）
 *
 *  PluCsvOutput の bytes を base64 エンコードして返す。
 *  フロントエンド側で base64デコード → native save dialog の保存先へ書き込む。
 */
export type PluExportPrepareResponse = {
	// CP932バイト列のbase64エンコード
	bytes_base64: string,
	// 推奨ファイル名（例: "PLU_20260408.txt"）
	suggested_filename: string,
	// MIMEタイプ
	content_type: string,
	// 文字エンコーディング名
	encoding: string,
	// 書出し件数
	count: number,
	// PLUファイルに含めた商品コード一覧
	target_product_codes: string[],
	// PLUファイルに含めなかった商品一覧
	excluded: PluExcludedProductResponse[],
	// PLU上限超過警告（互換維持フィールド）
	over_limit_warning: boolean,
};

// フロントエンドに返すプレビューデータ
export type PreviewData = {
	file_info: FileInfo,
	matched_summary: MatchedSummary,
	error_summary: ErrorSummary,
	duplicate_check: DuplicateCheck,
	preview_created_at: string,
};

/**
 *  商品マスタの行マッピング（products テーブル全18カラム）
 *
 *  db-design/master-tables.md products
 */
export type Product = {
	product_code: string,
	jan_code: string | null,
	name: string,
	department_id: number,
	supplier_id: number | null,
	selling_price: number,
	cost_price: number,
	tax_rate: string,
	maker_code: string | null,
	stock_quantity: number,
	stock_unit: string,
	is_discontinued: boolean,
	plu_dirty: boolean,
	plu_exported_at: string | null,
	plu_target: boolean,
	pos_stock_sync: boolean,
	created_at: string,
	updated_at: string,
};

// 商品登録リクエスト（FUNC-4.2）
export type ProductCreateRequest = {
	jan_code: string | null,
	name: string,
	department_id: number,
	selling_price: number,
	cost_price: number,
	tax_rate: string,
	stock_unit: string,
	initial_stock: number,
	maker_code: string | null,
	supplier_id: number | null,
	pos_stock_sync: boolean,
	plu_target: boolean,
};

// 商品登録結果（FUNC-4.2）
export type ProductCreateResult = {
	product_code: string,
	warnings: string[],
};

// インポート結果
export type ProductImportResult = {
	created_count: number,
	updated_count: number,
	skipped_count: number,
};

// PLU dirty 商品レスポンス（フロントエンド返却用）
export type ProductResponse = {
	product_code: string,
	jan_code: string | null,
	name: string,
	department_id: number,
	selling_price: number,
	cost_price: number,
	stock_quantity: number,
	plu_dirty: boolean,
	plu_exported_at: string | null,
};

/**
 *  商品検索条件
 *
 *  20-io-product-repo.md §2.3 search_products
 */
export type ProductSearchQuery = {
	// 商品名/product_code/jan_code の部分一致
	keyword: string | null,
	department_id: number | null,
	// None=全件、Some(false)=現行品のみ、Some(true)=廃番のみ
	is_discontinued: boolean | null,
	sort_key: SortKey,
	sort_order: SortOrder,
	// 1始まり。0以下は DbError::QueryFailed
	page: number,
	// 1以上。0は DbError::QueryFailed。デフォルト50
	per_page: number,
};

// 商品更新リクエスト（FUNC-4.4）
export type ProductUpdateRequest = ProductUpdateRequest_Serialize | ProductUpdateRequest_Deserialize;

// 商品更新リクエスト（FUNC-4.4）
export type ProductUpdateRequest_Deserialize = {
	name: string | null,
	department_id: number | null,
	supplier_id?: number | null,
	selling_price: number | null,
	cost_price: number | null,
	tax_rate: string | null,
	maker_code?: string | null,
	pos_stock_sync: boolean | null,
	plu_target: boolean | null,
};

// 商品更新リクエスト（FUNC-4.4）
export type ProductUpdateRequest_Serialize = {
	name: string | null,
	department_id: number | null,
	supplier_id: number | null,
	selling_price: number | null,
	cost_price: number | null,
	tax_rate: string | null,
	maker_code: string | null,
	pos_stock_sync: boolean | null,
	plu_target: boolean | null,
};

// 商品更新結果（FUNC-4.4）
export type ProductUpdateResult = {
	warnings: string[],
};

/**
 *  商品 + 部門名 + 取引先名（LEFT JOIN結果）
 *
 *  20-io-product-repo.md §2.3 find_by_product_code
 */
export type ProductWithRelations = {
	department_name: string,
	supplier_name: string | null,
} & (Product);

// 入庫記録リクエスト（31-biz-inventory-service.md §12.3）
export type ReceivingCreateRequest = {
	idempotency_key: string,
	supplier_id: number | null,
	receiving_date: string,
	note: string | null,
	items: ReceivingItemInput[],
};

// 入庫記録の結果
export type ReceivingCreateResult = {
	record_id: number,
	created: boolean,
	idempotent_replay: boolean,
	stock_warnings: string[],
};

export type ReceivingItemInput = {
	product_code: string,
	quantity: number,
	cost_price: number,
};

// 入庫記録詳細
export type ReceivingRecordDetail = {
	id: number,
	receiving_date: string,
	supplier_id: number | null,
	supplier_name: string | null,
	note: string | null,
	status: string,
	created_at: string,
	items: ReceivingRecordDetailItem[],
	total_cost: number,
	movements: MovementRecord[],
};

// 入庫記録詳細の明細行
export type ReceivingRecordDetailItem = {
	id: number,
	product_code: string,
	product_name: string,
	department_name: string,
	stock_unit: string,
	quantity: number,
	cost_price: number,
	line_cost: number,
};

// 入庫記録一覧表示用（supplier_name JOIN済み）
export type ReceivingRecordWithSupplier = {
	id: number,
	supplier_id: number | null,
	supplier_name: string | null,
	receiving_date: string,
	note: string | null,
	created_at: string,
};

export type RestoreBackupRequest = {
	backup_path: string,
};

// 返品・交換記録リクエスト（31-biz-inventory-service.md §12.4）
export type ReturnCreateRequest = {
	idempotency_key: string,
	return_type: string,
	return_date: string,
	register_processed: boolean,
	receipt_image_path: string | null,
	note: string | null,
	items: ReturnItemInput[],
};

// 返品・交換記録の結果
export type ReturnCreateResult = {
	record_id: number,
	created: boolean,
	idempotent_replay: boolean,
	stock_warnings: string[],
};

export type ReturnItemInput = {
	product_code: string,
	direction: string,
	quantity: number,
};

// 返品・交換記録詳細
export type ReturnRecordDetail = {
	id: number,
	return_type: string,
	return_date: string,
	register_processed: boolean,
	receipt_image_path: string | null,
	note: string | null,
	status: string,
	created_at: string,
	items: ReturnRecordDetailItem[],
	movements: MovementRecord[],
};

// 返品・交換記録詳細の明細行
export type ReturnRecordDetailItem = {
	id: number,
	product_code: string,
	product_name: string,
	department_name: string,
	stock_unit: string,
	direction: string,
	quantity: number,
};

// 返品記録一覧表示用
export type ReturnRecordSummary = {
	id: number,
	return_type: string,
	return_date: string,
	register_processed: boolean,
	note: string | null,
	created_at: string,
};

// rollback_csv_import の結果
export type RollbackResult = {
	success: boolean,
	voided_sale_count: number,
	voided_movement_count: number,
	stock_corrections: StockCorrection[],
};

/**
 *  売上CSVエクスポートレスポンス（フロントエンド返却用）
 *
 *  csv_bytes を base64 エンコードして返す。
 *  フロントエンド側で base64デコード → Blob → ダウンロード保存する。
 */
export type SalesExportResponse = {
	// UTF-8 BOM付きCSVバイト列のbase64エンコード
	bytes_base64: string,
	// 推奨ファイル名
	suggested_filename: string,
	// MIMEタイプ
	content_type: string,
	// 文字エンコーディング名
	encoding: string,
	// エクスポート件数
	record_count: number,
};

/**
 *  集計モード
 *
 *  response serialize 時に snake_case 出力（"by_product" / "by_department"）。
 *  request 引数は `get_monthly_sales(mode: String)` で受け取り CMD 層で変換する（H-1）。
 */
export type SalesMode = "by_product" | "by_department";

/**
 *  レポート種別（CSVエクスポート用）
 *
 *  `serde::Deserialize` + `specta::Type` + `#[serde(rename_all = "snake_case")]` で
 *  frontend bindings から `"daily" | "monthly_by_product" | "monthly_by_department"` literal union として
 *  受け取り、CMD 層で文字列 validation なく直接 enum として deserialize される（H-5 / Q-6 A 案）。
 */
export type SalesReportType =
// 日次（target: YYYY-MM-DD）
"daily" |
// 月次・商品別（target: YYYY-MM）
"monthly_by_product" |
// 月次・部門別（target: YYYY-MM）
"monthly_by_department";

export type SaveImageRequest = {
	image_base64: string,
	extension: string,
};

export type SaveImageResponse = {
	relative_path: string,
};

// 検索ソートキー
export type SortKey = "Name" | "ProductCode" | "StockQuantity" | "SellingPrice";

// 検索ソート順
export type SortOrder = "Asc" | "Desc";

// 棚卸し開始結果
export type StartStocktakeResult = {
	stocktake_id: number,
	item_count: number,
	auto_filled_count: number,
};

// 在庫補正詳細
export type StockAdjustment = {
	product_code: string,
	old_stock: number,
	new_stock: number,
	adjustment: number,
};

// 在庫補正の詳細（rollback結果に含まれる）
export type StockCorrection = {
	product_code: string,
	old_stock: number,
	new_stock: number,
};

/**
 *  在庫詳細（商品情報 + 最終入庫日 + 最終販売日）
 *
 *  44-cmd-inventory.md §23.9 get_stock_detail
 */
export type StockDetail = {
	product: ProductWithRelations,
	last_receiving_date: string | null,
	last_sale_date: string | null,
};

/**
 *  棚卸しヘッダの行マッピング
 *
 *  db-design/tracking-system-tables.md stocktakes
 */
export type Stocktake = {
	id: number,
	started_at: string,
	completed_at: string | null,
	status: string,
	total_cost: number | null,
};

/**
 *  棚卸し明細（商品名・部門名付き、一覧表示用）
 *
 *  20-io-product-repo.md §2.11
 */
export type StocktakeItemDetail = {
	id: number,
	stocktake_id: number,
	product_code: string,
	name: string,
	department_name: string,
	system_stock: number,
	actual_count: number | null,
	counted_at: string | null,
	current_stock: number,
};

/**
 *  棚卸しアイテム一覧レスポンス（CMD-10 get_stocktake_items 専用）
 *
 *  items（PaginatedResult相当）+ progress を1レスポンスにまとめる。
 */
export type StocktakeItemListResponse = {
	items: StocktakeItemDetail[],
	progress: StocktakeProgress,
	total_count: number,
	page: number,
	per_page: number,
};

// 棚卸し進捗
export type StocktakeProgress = {
	total_items: number,
	counted_items: number,
	uncounted_items: number,
};

// 棚卸し確定結果
export type StocktakeResult = {
	total_cost: number,
	adjusted_items: AdjustedItem[],
	total_items: number,
	// D-2統合: 確定後の整合性チェック結果。失敗時はNone
	integrity_result: IntegrityResult | null,
};

/**
 *  取引先マスタの行マッピング
 *
 *  db-design/master-tables.md suppliers
 */
export type Supplier = {
	id: number,
	name: string,
	created_at: string,
};

// カウント更新結果
export type UpdateCountResult = {
	success: boolean,
	current_difference: number,
};

export type UpdateSettingRequest = {
	key: string,
	value: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
